image: gitpod/workspace-mysql

tasks:
  - init: |
      npm install
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev
    env: 
      DATABASE_URL: mysql://gitpod@localhost/todos

ports:
  - port: 3000
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
vscode:
  extensions:
    - svelte.svelte-vscode
    - vscodevim.vim
    - Prisma.prisma


github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
