image: gitpod/workspace-postgres

tasks:
  - init: |
      npm install
    command: |
      export HMR_HOST=`gp url 3000`
      export OAUTH_REDIRECT_URI=`gp url 3000`"/api/auth-callback"
      npm run dev
    env: 
      DATABASE_URL: postgres://gitpod@localhost/todos
      

ports:
  - port: 3000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore
vscode:
  extensions:
    - svelte.svelte-vscode
    - vscodevim.vim
    - Prisma.prisma


github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
